/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * nsINoiseCipherState
 * This interface provides the Noise protocol's CipherState type.
 *
 * https://noiseprotocol.org/noise.html#the-cipherstate-object
 */

[scriptable, uuid(88c21d1d-fc4d-46b4-8f13-4c4fd4cdfbd4)]
interface nsINoiseCipherState : nsISupports
{
    /**
     * `true` if the key has been set.
     */
    readonly attribute boolean hasKey;

    void initializeKey(in Array<octet> key);

    void setNonce(in uint64_t nonce);

    Array<octet> encryptWithAd(
        in Array<octet> ad,
        in Array<octet> plaintext);

    Array<octet> decryptWithAd(
        in Array<octet> ad,
        in Array<octet> cipherText);
    
    // Not used in caBLE
    // void rekey();
};
